name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bounce:
    path: ../

  cupertino_icons: ^1.0.2
  motion: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:

  uses-material-design: true