name: bounce
description: A widget that animates its children with a smooth scale and rotate animation, depending on the location of the touch.
version: 1.0.0
homepage: https://cendre.me
repository: https://github.com/mrcendre/bounce
issue_tracker: https://github.com/mrcendre/bounce/issues?q=is%3Aissue+is%3Aopen
environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter: